language: go
go:
- 1.3.3
- tip
env:
- PATH=$HOME/gopath/bin:$PATH
script:
- make dep
- make build
- make test
notifications:
  email: false
  slack:
    secure: oqsn3JRtNE4H4GrdkqGQ8FrZeL1gkr0xd6z6OiJLDYblu7HV5IvRtW0PH71NatHPM6FJ/tIBnI6ZqZfY0zwkiFdyCrQLzkQHAGJ0GqCA8+gfRhPc9+Wg60CWj1in3iFDx+ObTF9zW1j87e7QhxkT8EunTzf4+PD1XZWmUBqL7P8=
